### ISSUE TITLE
mitosign files from MIP to Scout load config

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/cg#1586]
## Description

mitosign mitodel txt files that are already produced by MIP 11 should be added to individuals in the Scout load config.

## Suggested solution

Add a key `mitodel_file` to the scout load config sample which have them from hk. Available in Hermes / hk as `mitodel` (mip deliverable `mitodel`.

```
samples:
 - analysis_type: wgs
   sample_id: NA12882
   mitodel_file: scout/demo/mitodel_test_files/hugelymodelbat_lanes_1_sorted_md_mitodel.txt
```

## This can be closed when

Mitodel files are loaded to scout and can be visualised in mt reports as in https://github.com/Clinical-Genomics/scout/pull/3573.
