### ISSUE TITLE
Store analysis output-files from Balsamic in Housekeeper

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/cg#475]
As a TA member, I would like to have files from Balsamic runs added to HK so that they are easy to find/deliver etc

Problem: the Balsamic pipeline is now being set up. The output files from this shall be stored in Housekeeper just as the files from MIP.

Information:
Dir-structure for Balsamic
fastq's: /home/proj/production/cancer/analysis/case-id/fastq/
results: /home/proj/production/cancer/analysis/case-id/analysis/
job logs: /home/proj/production/cancer/analysis/case-id/logs/
job scripts: /home/proj/production/cancer/analysis/case-id/scripts/
Internal BALSAMIC log: job logs: /home/proj/production/cancer/analysis/case-id/BALSAMIC_run

How to know when an analysis is finished:
I asked Hassan to make Balsamic create a file when an analysis is completed, for example 'analysis_finish' in case-directory (we need to know if this is on sample or case level)
He has created an issue on GitHub:
https://github.com/Clinical-Genomics/BALSAMIC/issues/143

Suggested solution:

    Use Balsamic root directory in cg config file
    Let 'store-completed.sh' store also Balsamic files in HK
    Let cg store analysis use Analysis Type to figure out what to store.
    Add an extra tag to the files in HK to differentiate between pipelines, for example mip/balsamic - apply tags also to old files
    Make sure the 'cg store' crontab is working
    Parse the .hk file for things to store in housekeeper. Example /home/proj/production/cancer/cases/rapidghost/analysis/delivery_report/rapidghost.hk
    Check existing code for interactions with bundles to make sure that we don't introduce bugs when using latest bundle version - what happens if there are two bundle versions with the same date? -> solve this by having the order portal make two cases if Balsamic and MIP is ordered for the same sample and add data analysis on case level (new user story @ingkebil).
    add a move to trash of analysis folder at end of storage.
    document in balsamic method
    make a US that adds cg store completed

There will be a delivery_report directory in /home/proj/production/cancer/analysis/<case name>/analysis/ with a file <casename>.hk which is a yaml-file with keys:

    vcf
    bam
    multiqc
    scout
    other
        pdfs

Check if tests exist in cg: other US will be made by KB

Q: What do we need to store?
A: We should ask HFA before starting the US
Q2: is the .hk already created?
A2:

DoD:
Files from Balsamic are stored in HK after finished analysis
A pipeline-tag has been added to the files in HK
Verified

How to demo:
Show
$ housekeeper get balsamic case bundle

**Comment by hassanfa** [comment]
@henrikstranneheim This is the structure I have for BALSAMIC. Files section is for housekeeper to store. And key names are going to be directory path to keep'em organized and tidy.

How do you have it in MIP?

```
files:
  bam:
  - /home/hassan.foroughi/repos/BALSAMIC/run_tests/benchmark_filename_revamp_single/analysis/bam/tumor.sorted.mrkdup.ralgn.bsrcl.merged.bam
  - /home/hassan.foroughi/repos/BALSAMIC/run_tests/benchmark_filename_revamp_single/analysis/bam/tumor.merged.bam
  cnv:
  - /home/hassan.foroughi/repos/BALSAMIC/run_tests/benchmark_filename_revamp_single/analysis/cnv/tumor.merged-scatter.pdf
  - /home/hassan.foroughi/repos/BALSAMIC/run_tests/benchmark_filename_revamp_single/analysis/cnv/tumor.merged-diagram.pdf
  qc:
  - /home/hassan.foroughi/repos/BALSAMIC/run_tests/benchmark_filename_revamp_single/analysis/qc/multiqc_data
  - /home/hassan.foroughi/repos/BALSAMIC/run_tests/benchmark_filename_revamp_single/analysis/qc/multiqc_report.html
  scout:
  - /home/hassan.foroughi/repos/BALSAMIC/run_tests/benchmark_filename_revamp_single/analysis/scout/benchmark_filename_revamp_single.scout.yaml
  vcf:
  - /home/hassan.foroughi/repos/BALSAMIC/run_tests/benchmark_filename_revamp_single/analysis/vcf/SNV.germline.S1_R.haplotypecaller.vcf.gz
  vep:
  - /home/hassan.foroughi/repos/BALSAMIC/run_tests/benchmark_filename_revamp_single/analysis/vep/SNV.germline.S1_R.haplotypecaller.vcf.gz
  - /home/hassan.foroughi/repos/BALSAMIC/run_tests/benchmark_filename_revamp_single/analysis/vep/SV.germline.S1_R.manta_germline.vcf.gz
  - /home/hassan.foroughi/repos/BALSAMIC/run_tests/benchmark_filename_revamp_single/analysis/vep/SNV.somatic.benchmark_filename_revamp_single.mutect.vcf.gz
  - /home/hassan.foroughi/repos/BALSAMIC/run_tests/benchmark_filename_revamp_single/analysis/vep/SNV.somatic.benchmark_filename_revamp_single.vcfmerge.vcf.gz
  - /home/hassan.foroughi/repos/BALSAMIC/run_tests/benchmark_filename_revamp_single/analysis/vep/SNV.somatic.benchmark_filename_revamp_single.vardict.vcf.gz
  - /home/hassan.foroughi/repos/BALSAMIC/run_tests/benchmark_filename_revamp_single/analysis/vep/SNV.germline.S1_R.strelka_germline.vcf.gz
  - /home/hassan.foroughi/repos/BALSAMIC/run_tests/benchmark_filename_revamp_single/analysis/vep/SV.somatic.benchmark_filename_revamp_single.manta.vcf.gz
  - /home/hassan.foroughi/repos/BALSAMIC/run_tests/benchmark_filename_revamp_single/analysis/vep/SNV.somatic.benchmark_filename_revamp_single.vcfmerge.balsamic_stat
meta:
  key_1:
  key_2:
  key_3:
```

**Comment by henrikstranneheim** [comment]
Here is my suggestion:
```
store:
  - format: <fastq|bam|vcf|meta|"whatever_makes_sense"> "#String"
    level: <sample_id|case_id|project_id> "#String"
    path: /a/absolute/path/to/analysis_file "#String"
    path_index: /a/path/to/analysis_file.index_suffix "#String" 
  - format: bam
    level: sample_1
    path: /mip_analysis/sample_1/bwa_mem/sample_1.bam
    path_index: /mip_analysis/sample_1/bwa_mem/sample_1.bam.bai
```

The point here is that the file produced by the workflows can have from 1 to n files where each file can have a set of mandatory keys and values (if we like), but also other keys describing each file whenever appropriate. I think this will be more maintainable and extendible while still bringing consistency across workflows and the code that operates on this file. 

@hassanfa @jemten @barrystokman @patrikgrenfeldt @sylvinite What do you think of this?
